###############################################################################
# Copyright (c) 2022, 2024 SWTChart project
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0/.
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Matthias Mailänder - initial API and implementation
###############################################################################

name: Continuous Integration
on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout SWTChart
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.2

    - name: Build with Maven
      uses: coactions/setup-xvfb@v1
      with:
        run: mvn -f org.eclipse.swtchart.cbi/pom.xml -T 1C verify --batch-mode --no-transfer-progress
